from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register, name='register'),
    path('contact-us', views.contact, name='contact'),
    path('terms-of-service', views.terms_of_service, name='terms_of_service'),
    path('privacy-policy', views.privacy_policy, name='privacy_policy'),
    path('forgot-password', views.forgot_password, name='forgot_password'),
    path('reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),

    # Admin
    path('admin/dashboard', views.dashboard, name='dashboard'),
    path('admin/add-product', views.add_product, name='add_product'),
    path('admin/edit-product/<str:product_id>', views.edit_product, name='edit_product'),
    path('admin/edit-bundle/<str:bundle_id>', views.edit_bundle, name='edit_bundle'),
    path('admin/add-bundle', views.add_bundle, name='add_bundle'),
    path('admin/add-category', views.add_category, name='add_category'),
    path('admin/product-list', views.product_list, name='product_list'),
    path('admin/bundle-list', views.bundle_list, name='bundle_list'),
    path('admin/category-list', views.category_list, name='category_list'),
    path('admin/user-list', views.user_list, name='user_list'),
    path('admin/banned-user-list', views.banned_user_list, name='banned_user_list'),
    path('admin/admin-list', views.admin_list, name='admin_list'),
    path('admin/register', views.register_admin, name='register_admin'),
    path('admin/edit-profile', views.admin_edit_profile, name='admin_edit_profile'),
    path('admin/change-password', views.admin_change_password, name='admin_change_password'),
    path('admin/activity-logs', views.activity_logs, name='activity_logs'),
    path('admin/picked-up-orders', views.completed_orders, name='completed_orders'),
    path('admin/cancelled-orders', views.cancelled_orders, name='cancelled_orders'),
    path('admin/pending-orders', views.pending_orders, name='pending_orders'),
    path('admin/to-pack-orders', views.to_pack_orders, name='to_pack_orders'),
    path('admin/ready-to-pickup-orders', views.ready_for_pickup_orders, name='ready_for_pickup_orders'),
    path('admin/edit-order/<str:order_id>', views.edit_order, name='edit_order'),
    path('admin/ban-user/<str:user_id>', views.ban_user, name='ban_user'),
    path('admin/unban-user/<str:user_id>', views.unban_user, name='unban_user'),
    path('admin/delete-product/<str:product_id>', views.delete_product, name='delete_product'),
    path('admin/edit-category/<int:category_id>', views.edit_category, name='edit_category'),

    # User
    path('shop', views.shop, name='shop'),
    path('cart', views.cart, name='cart'),
    path('product/<str:product_id>', views.product, name='product'),
    path('add-to-cart', views.add_to_cart, name='add_to_cart'),
    path('update-cart', views.update_cart, name='update_cart'),
    path('delete-cart', views.delete_cart, name='delete_cart'),
    path('checkout-product', views.add_to_checkout_cart, name='add_to_checkout_cart'),
    path('guest-checkout', views.guest_checkout, name='guest_checkout'),
    path('checkout-now', views.add_to_checkout_now, name='add_to_checkout_now'),
    path('remove-from-checkout-cart', views.remove_from_checkout_cart, name='remove_from_checkout_cart'),
    path('checkout-products', views.checkout, name='checkout'),
    path('profile', views.profile, name='profile'),
    path('change-password', views.user_change_password, name='user_change_password'),
    path('delete-order', views.soft_delete_order, name='soft_delete_order'),
    path('search-products', views.search_products, name='search_products'),
    path('search-bundles', views.search_bundles, name='search_bundles'),
    path('get-order-counts', views.get_order_counts, name='get_order_counts'),
    path('submit-review', views.submit_review, name='submit_review'),
    path('remove-review', views.remove_review, name='remove_review'),

    # path('page-not-found', views.error_404, name='error_404'),
    # path('internal-server-error', views.error_500, name='error_500'),
]